# Generated by Django 4.0 on 2022-06-19 15:22

from django.db import migrations, models
import subscribe.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], default='W', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='last_name',
            field=models.CharField(max_length=100, validators=[subscribe.models.validate_comma]),
        ),
    ]
