# Generated by Django 4.0 on 2022-06-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
